package view;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;


import core.Client;
import core.HitsResult;
import core.HitsResults;
import core.ServerAnswer;

/**
 *
 * @author ujarky
 */
public class ClientWindow extends JFrame {

    /**
     * Creates new form ClientWindow
     */
    public ClientWindow() {
        this.initComponents();
        this.client = new Client();
        this.pages = new HitsResults();
        this.order = true;
        this.initServerDataConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jrbGroup = new javax.swing.ButtonGroup();
        jPanelNorth = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jtQuery = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jtDepth = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbSend = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jbErase = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jtServerIP = new javax.swing.JLabel();
        jtServerPort = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jrbAut = new javax.swing.JRadioButton();
        jrbHub = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jaResults = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiEdit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Engine");
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(700, 500));

        jPanelNorth.setBackground(new java.awt.Color(50, 56, 58));
        jPanelNorth.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(51, 57, 58));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 237));
        jLabel1.setText("Search");
        jPanel3.add(jLabel1);

        jPanelNorth.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel12.setBackground(new java.awt.Color(51, 57, 58));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jPanel11.setBackground(new java.awt.Color(51, 57, 58));

        jPanel2.setBackground(new java.awt.Color(51, 57, 57));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(238, 238, 237));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Query");
        jPanel2.add(jLabel5, java.awt.BorderLayout.NORTH);

        jPanel13.setBackground(new java.awt.Color(51, 57, 58));

        jtQuery.setBackground(new java.awt.Color(51, 57, 58));
        jtQuery.setColumns(25);
        jtQuery.setForeground(new java.awt.Color(254, 255, 255));
        jtQuery.setText("Variedades-Monica");
        jtQuery.setToolTipText("");
        jPanel13.add(jtQuery);

        jPanel2.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel2);

        jPanel14.setBackground(new java.awt.Color(51, 57, 58));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel6.setForeground(new java.awt.Color(238, 238, 238));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Depth");
        jLabel6.setToolTipText("");
        jPanel14.add(jLabel6, java.awt.BorderLayout.NORTH);

        jPanel15.setBackground(new java.awt.Color(51, 57, 58));

        jtDepth.setBackground(new java.awt.Color(51, 57, 58));
        jtDepth.setColumns(3);
        jtDepth.setForeground(new java.awt.Color(254, 255, 255));
        jtDepth.setToolTipText("");
        jPanel15.add(jtDepth);

        jPanel14.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel14);

        jPanel12.add(jPanel11);

        jPanelNorth.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(51, 57, 58));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jbSend.setBackground(new java.awt.Color(51, 57, 58));
        jbSend.setForeground(new java.awt.Color(14, 173, 219));
        jbSend.setText("Send");
        jbSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSendActionPerformed(evt);
            }
        });
        jPanel1.add(jbSend);

        jPanelNorth.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelCenter.setBackground(new java.awt.Color(51, 57, 58));
        jPanelCenter.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(51, 57, 58));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(51, 57, 57));
        jPanel7.setBorder(null);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jSeparator1.setBackground(new java.awt.Color(33, 37, 39));
        jSeparator1.setForeground(new java.awt.Color(238, 238, 235));
        jPanel7.add(jSeparator1, java.awt.BorderLayout.NORTH);

        jPanel4.add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(51, 57, 58));
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jPanel22.setBackground(new java.awt.Color(51, 57, 58));
        jPanel5.add(jPanel22);

        jPanel21.setBackground(new java.awt.Color(51, 57, 58));

        jbErase.setBackground(new java.awt.Color(51, 57, 58));
        jbErase.setForeground(new java.awt.Color(255, 0, 49));
        jbErase.setText("Erase");
        jbErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEraseActionPerformed(evt);
            }
        });
        jPanel21.add(jbErase);

        jPanel5.add(jPanel21);

        jPanel4.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel17.setBackground(new java.awt.Color(51, 57, 57));
        jPanel17.setLayout(new java.awt.GridLayout(2, 1));

        jPanel20.setBackground(new java.awt.Color(51, 57, 57));
        jPanel20.setLayout(new java.awt.GridLayout(2, 1));
        jPanel17.add(jPanel20);

        jPanel19.setBackground(new java.awt.Color(51, 57, 57));
        jPanel19.setLayout(new java.awt.GridLayout(2, 1));

        jtServerIP.setText("Server IP:");
        jPanel19.add(jtServerIP);

        jtServerPort.setText("Server port:");
        jPanel19.add(jtServerPort);

        jPanel17.add(jPanel19);

        jPanel4.add(jPanel17, java.awt.BorderLayout.WEST);

        jPanel6.setBackground(new java.awt.Color(51, 57, 58));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(51, 57, 57));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(51, 57, 58));
        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 4));

        jLabel2.setBackground(new java.awt.Color(51, 57, 58));
        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Results");
        jPanel10.add(jLabel2);

        jPanel16.add(jPanel10, java.awt.BorderLayout.NORTH);

        jPanel9.setBackground(new java.awt.Color(51, 57, 58));
        jPanel9.setBorder(null);
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel3.setText("Order by");
        jPanel9.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel18.setBackground(new java.awt.Color(51, 57, 58));
        jPanel18.setBorder(null);
        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel4.setText("Order by");
        jPanel18.add(jLabel4);

        jPanel9.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel8.setBackground(new java.awt.Color(51, 57, 58));
        jPanel8.setBorder(null);
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jrbGroup.add(jrbAut);
        jrbAut.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jrbAut.setSelected(true);
        jrbAut.setText("Autorythies");
        jrbAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAutActionPerformed(evt);
            }
        });
        jPanel8.add(jrbAut);

        jrbGroup.add(jrbHub);
        jrbHub.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jrbHub.setText("Hub");
        jrbHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHubActionPerformed(evt);
            }
        });
        jPanel8.add(jrbHub);

        jPanel9.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanelCenter.add(jPanel4, java.awt.BorderLayout.NORTH);

        jaResults.setEditable(false);
        jaResults.setBackground(new java.awt.Color(34, 38, 40));
        jaResults.setColumns(20);
        jaResults.setForeground(new java.awt.Color(255, 254, 255));
        jaResults.setRows(5);
        jScrollPane1.setViewportView(jaResults);

        jPanelCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(51, 57, 58));
        jMenuBar1.setForeground(new java.awt.Color(238, 238, 235));

        jMenu1.setBackground(new java.awt.Color(51, 57, 58));
        jMenu1.setText("Server");

        jmiEdit.setBackground(new java.awt.Color(51, 57, 58));
        jmiEdit.setText("Edit");
        jmiEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditActionPerformed(evt);
            }
        });
        jMenu1.add(jmiEdit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initServerDataConnection(){
        try {
            //CAMBIAR LUEGO POR TU IP ADRESS
            String serverHost = InetAddress.getLocalHost().getHostAddress();
            setServerDataConnection(serverHost, 1213);
        } catch (UnknownHostException ex) {
            ex.getStackTrace();
            Logger.getLogger(ClientWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setServerDataConnection(String serverIP, int serverPort){
        this.client.setServerIP(serverIP);
        this.client.setServerPort(serverPort);
        this.jtServerIP.setText("Server IP: "+ serverIP);
        this.jtServerPort.setText("Server Port: "+ serverPort);

    }
    
    public int getDepth(){
        int depth = 0;
        try{
            depth = Integer.parseInt(this.jtDepth.getText());
        }catch(Exception e){
            this.jtDepth.setText("0");
        }
        return depth;
    }
    
    public Client getClient() {
        return this.client;
    }
    
    public void sortPages(){
        if(this.order){
            this.pages.sortPagesByAuthority();
        }else{
            this.pages.sortPagesByHub();
        }
        this.jaResults.append("\n-------------------Pagers Order By "+((this.order)?"Authorities":"Hub") + "-------------------\n");
        this.jaResults.append("#\tAuthority\tHub\t\t\tURL\n");
        int c = 1;
        for (HitsResult page : this.pages.getPages()) {
          this.jaResults.append(c+"\t" + page.getStringToTable()+ "\n");
          c++;
        }
        this.jaResults.append("\tAuthority\tHub\t\t\tURL\n");
    }
    
    private void addServerAnswer(ServerAnswer serverAnswer){
        this.pages.clearList();
        this.jaResults.append("Query: " + this.jtQuery.getText() + " sent to server whit depth " +getDepth() +"\n" );

        if(serverAnswer.getAnswerType() != null ){
           this.jaResults.append("Receaved: " + serverAnswer.getAnswerType() +"\n");
           if(!serverAnswer.isError()){
                pages.setPagesByJson(serverAnswer.getAnswerContent());
                sortPages();
           }else{
                this.jaResults.append(serverAnswer.getAnswerContent() + "\n");
           }
        }else{
            this.jaResults.append("\n**********ERROR*************\nany response receaved\n");
        }
    }
    
    private void jmiEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditActionPerformed
       ServerEditionWindow serverEditionWindow = new ServerEditionWindow(this, false);
    }//GEN-LAST:event_jmiEditActionPerformed

    private void jbSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSendActionPerformed
       this.addServerAnswer(this.client.getAnswerByQuery(this.jtQuery.getText(), getDepth()));
    }//GEN-LAST:event_jbSendActionPerformed

    private void jrbAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAutActionPerformed
        this.order = true;
        sortPages();
    }//GEN-LAST:event_jrbAutActionPerformed

    private void jrbHubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHubActionPerformed
        this.order = false;
        sortPages();
    }//GEN-LAST:event_jrbHubActionPerformed

    private void jbEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEraseActionPerformed
        this.jaResults.setText("");
    }//GEN-LAST:event_jbEraseActionPerformed



    
    
    private Client client;
    private HitsResults pages;
    private boolean order;
           
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jaResults;
    private javax.swing.JButton jbErase;
    private javax.swing.JButton jbSend;
    private javax.swing.JMenuItem jmiEdit;
    private javax.swing.JRadioButton jrbAut;
    private javax.swing.ButtonGroup jrbGroup;
    private javax.swing.JRadioButton jrbHub;
    private javax.swing.JTextField jtDepth;
    private javax.swing.JTextField jtQuery;
    private javax.swing.JLabel jtServerIP;
    private javax.swing.JLabel jtServerPort;
    // End of variables declaration//GEN-END:variables
}
