package view;

/**
 *
 * @author ujarky
 */
public class ServerEditionWindow extends javax.swing.JDialog {

    /**
     * Creates new form ServerEditionWindow
     */
    private ClientWindow parent;
    public ServerEditionWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = (ClientWindow) parent;
        initComponents();
        initTextFields();
        setVisible(true);
        

    }
    
    private void initTextFields(){
        this.jtServerIP.setText(parent.getClient().getServerIP());
        this.jtServerPort.setText(parent.getClient().getServerPort()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbAcept = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtServerIP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtServerPort = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(300, 200));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(51, 57, 58));

        jLabel1.setForeground(new java.awt.Color(238, 238, 237));
        jLabel1.setText("Server Edition");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel7.setBackground(new java.awt.Color(51, 57, 57));

        jbAcept.setBackground(new java.awt.Color(51, 57, 58));
        jbAcept.setForeground(new java.awt.Color(238, 238, 238));
        jbAcept.setText("Accept");
        jbAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptActionPerformed(evt);
            }
        });
        jPanel7.add(jbAcept);

        jbCancel.setBackground(new java.awt.Color(51, 57, 58));
        jbCancel.setForeground(new java.awt.Color(238, 238, 238));
        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel7.add(jbCancel);

        jPanel1.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel3.setBackground(new java.awt.Color(51, 57, 58));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(51, 57, 58));
        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setBackground(new java.awt.Color(51, 57, 58));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setForeground(new java.awt.Color(238, 238, 237));
        jLabel3.setText("Server IP    ");
        jPanel5.add(jLabel3);

        jtServerIP.setBackground(new java.awt.Color(51, 57, 58));
        jtServerIP.setColumns(10);
        jtServerIP.setForeground(new java.awt.Color(255, 255, 254));
        jPanel5.add(jtServerIP);

        jPanel6.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(51, 57, 58));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setForeground(new java.awt.Color(238, 238, 237));
        jLabel2.setText("Server Port");
        jPanel4.add(jLabel2);

        jtServerPort.setBackground(new java.awt.Color(51, 57, 58));
        jtServerPort.setColumns(10);
        jtServerPort.setForeground(new java.awt.Color(255, 255, 254));
        jPanel4.add(jtServerPort);

        jPanel6.add(jPanel4);

        jPanel3.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptActionPerformed
        parent.setServerDataConnection(this.jtServerIP.getText().trim(),Integer.parseInt(this.jtServerPort.getText().trim()));
        this.dispose();
    }//GEN-LAST:event_jbAceptActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbAcept;
    private javax.swing.JButton jbCancel;
    private javax.swing.JTextField jtServerIP;
    private javax.swing.JTextField jtServerPort;
    // End of variables declaration//GEN-END:variables
}
